### ISSUE TITLE
update in the works? 

### ISSUE THREAD

**Issue by tim762** [SansegoTek/DFKQuestRunner#21]
im going to assume most of the issues i am having currently are due to Harmony networt,
main issue being that the script recognizes that my hero is ready to quest but cannot initiate the questing, same goes when a quest is complete it recognizes that it is complete but cannot actually complete. 

i did abit of testing since the network has been somewhat stable by running the script which should initiate my hero questing(which it hasnt been) then manually trying it through the game itself and being able to instantly quest. Same going for completing i run the script prior to completion it recognizes that quest is complete but cant complete it, i then go in game and am instantly able to complete the quest. 

Very much appreciate you guys for open sourcing this!

**Comment by paulnearney** [comment]
Hey, thanks for opening the issue! Harmony have recently increased the gas price to 30 gwei - you'll need to update this in the config file. Change the line that says:

`"gasPrice": 10000000000,`

to read

`"gasPrice": 30000000000,`

This should sort the immediate problem - otherwise, feel free to reopen the issue

**Comment by tim762** [comment]
Thank you very much! worked right away
